FROM jenkins/jenkins:2.319.1-jdk11
USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN jenkins-plugin-cli --plugins "cloudbees-folder antisamy-markup-formatter build-timeout credentials-binding timestamper ws-cleanup workflow-aggregator github-branch-source pipeline-stage-view git ssh-slaves matrix-auth pam-auth email-ext mailer blueocean docker-workflow configuration-as-code authorize-project "
# RUN jenkins-plugin-cli"
COPY ./jenkins.yaml /var/jenkins_home/casc_configs/jenkins.yaml
