AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppStackName:
    Type: String
    Default: defaulted-zachtest-app
  RepoID:
    Type: String
    Default: "zacherytcox/hello-beautiful"
  GitCommit:
    Type: String
    Default: Defaulted
  GitComment:
    Type: String
    Default: Defaulted
  GitBranch:
    Type: String
    Default: Defaulted
  LaunchTime:
    Type: String
    Default: Defaulted
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppStackName}-${AWS::AccountId}'
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
      Tags: 
        - Key: GitCommit
          Value: !Ref GitCommit
        - Key: GitComment
          Value: !Ref GitComment
        - Key: GitBranch
          Value: !Ref GitBranch
        - Key: LaunchTime
          Value: !Ref LaunchTime
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action:
          - s3:GetObject
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref Bucket
              - /*
Outputs:
  BucketOutput:
    Description: S3 Hosting Bucket name
    Value: !Ref Bucket
    Export:
      Name: !Sub '${AWS::StackName}-Bucket'
