AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RepoID:
    Type: String
  GitCommit:
    Type: String
  GitBranch:
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
      Tags: 
        - Key: GitCommit
          Value: !Ref GitCommit
        - Key: GitBranch
          Value: !Ref GitBranch
        - Key: RepoID
          Value: !Ref RepoID
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStore: 
        Location: !Ref Bucket
        Type: S3
      RoleArn: !GetAtt IAMRole.Arn
      RestartExecutionOnUpdate: True
      Stages: 
        - Name: Source
          Actions: 
            - Name: Source
              ActionTypeId: 
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref CodeStarConnection
                FullRepositoryId: !Ref RepoID
                BranchName: !Ref GitBranch
              Namespace: SourceVariables
              OutputArtifacts: 
                - Name: SourceOutput
        # - Name: Deploy
        #   Actions: 
        #     - Name: Deploy
        #       ActionTypeId: 
        #         Category: Build
        #         Owner: AWS
        #         Provider: CodeBuild
        #         Version: 1
        #       InputArtifacts: 
        #         - Name: SourceOutput
        #       Configuration:
        #         EnvironmentVariables: "[{\"name\":\"Release_ID\",\"value\":\"#{codepipeline.PipelineExecutionId}\",\"type\":\"PLAINTEXT\"},{\"name\":\"Commit_ID\",\"value\":\"#{SourceVariables.CommitId}\",\"type\":\"PLAINTEXT\"}]"
        #         ProjectName: !Ref CodeBuild
        - Name: Deploy
          Actions: 
            - Name: Deploy
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration: 
                ActionMode: "CREATE_UPDATE"
                StackName: !Sub ${AWS::StackName}-App
                RoleArn: !GetAtt IAMRole2.Arn
                ParameterOverrides: !Sub '{"GitCommit": "#{SourceVariables.CommitId}","GitBranch": "#{SourceVariables.BranchName}","RepoID": "#{SourceVariables.FullRepositoryName}"}'
                TemplatePath: SourceOutput::app/app.yaml
              InputArtifacts: 
                - Name: SourceOutput
        - Name: Data-Test
          Actions: 
            - Name: Test
              ActionTypeId: 
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts: 
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref CodeBuild2
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties: 
      ConnectionName: hello-beautiful
      ProviderType: GitHub
  IAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: 
              - codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Description: String
      Policies: 
        - PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Sid: AWSCloudTrailCreateLogStream20141101
              Effect: Allow
              Action:
              - '*'
              Resource:
              - '*'
          PolicyName: Policy
  IAMRole2:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service:
              - cloudformation.amazonaws.com
          Action: sts:AssumeRole
      Description: String
      Policies: 
        - PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:CreateBucket
              - s3:GetBucketPolicy
              - s3:PutBucketPolicy
              - s3:PutBucketTagging
              - s3:PutBucketWebsite
              Resource: arn:aws:s3:::*
          PolicyName: Policy
  IAMRole3:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: 
              - codebuild.amazonaws.com
          Action: sts:AssumeRole
      Description: String
      Policies: 
        - PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Sid: AWSCloudTrailCreateLogStream20141101
              Effect: Allow
              Action:
              - '*'
              Resource:
              - '*'
          PolicyName: Policy
        # - PolicyDocument:
        #     Version: '2012-10-17'
        #     Statement:
        #     - Effect: Allow
        #       Action:
        #       - logs:CreateLogGroup
        #       - logs:CreateLogStream
        #       Resource: "*"
        #   PolicyName: Policy
          
  # CodeBuild:
  #   Type: AWS::CodeBuild::Project
  #   Properties: 
  #     Artifacts: 
  #       Type: CODEPIPELINE
  #     Environment: 
  #       ComputeType: BUILD_GENERAL1_SMALL
  #       Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
  #       Type: LINUX_CONTAINER
  #     ServiceRole: !GetAtt IAMRole.Arn
  #     Source: 
  #       BuildSpec: !Sub |
  #         version: 0.2
  #         phases:
  #           build:
  #             commands:
  #               - echo Build started on `date`
  #               - echo $Commit_ID
  #               - ( set -o posix ; set ) | less
  #               - ls -alh
  #               - pwd
  #               - whoami
  #             finally:
  #               - echo This always runs even if the install command fails
  #       SourceIdentifier: pleaseworkforZach
  #       Type: CODEPIPELINE
  CodeBuild2:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts: 
        Type: CODEPIPELINE
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt IAMRole3.Arn
      Source: 
        BuildSpec: !Sub |
          version: 0.2
          env:
            variables:
              stack_name: "${AWS::StackName}-App"
          phases:
            install:
              commands:
                - ( set -o posix ; set )
                - echo Install started on `date`
                - aws cloudformation describe-stacks --stack $stack_name | jq -r '.Stacks | .[].StackStatus'
                - this_bucket=$(aws cloudformation describe-stacks --stack $stack_name --query 'Stacks[0].Outputs[?OutputKey==`BucketOutput`].OutputValue' | jq -r '.[]');aws s3 sync ./code s3://$this_bucket --exclude "*.DS_Store"
            post_build:
              commands:
                - echo Testing started on `date`
                - aws cloudformation describe-stacks --stack $stack_name | jq -r '.Stacks | .[].StackStatus'
                - if [ "$(aws cloudformation describe-stacks --stack $stack_name | jq -r '.Stacks | .[].StackStatus')" == 'UPDATE_COMPLETE' ] || [ "$(aws cloudformation describe-stacks --stack $stack_name | jq -r '.Stacks | .[].StackStatus')" == 'CREATE_COMPLETE' ] ;then echo Stack Completed Successfully; else exit 1; fi 
                - code=$(curl --write-out '%{http_code}' --silent --output /dev/null "$(aws cloudformation describe-stacks --stack $stack_name --query 'Stacks[0].Outputs[?OutputKey==`BucketOutput`].OutputValue' | jq -r '.[]').s3-website-us-east-1.amazonaws.com"/);if [ "$code" == '200' ];then echo "Homepage is active ($code)";else echo "Homepage errors ("$code")";exit 1;fi 
        SourceIdentifier: pleaseworkforZach
        Type: CODEPIPELINE